/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 deoC2.gltf 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function DeoC2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/deoC2.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["deo"].play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorig6Hips} />
          <skinnedMesh
            name="Ch09"
            geometry={nodes.Ch09.geometry}
            material={materials.Ch09_body}
            skeleton={nodes.Ch09.skeleton}
          />
        </group>
        <group
          name="Rokoko_Video_Character"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="Root">
            <primitive object={nodes.Hips} />
          </group>
        </group>
        <mesh
          name="Fitness_Grandma_EyesAnimGeo"
          geometry={nodes.Fitness_Grandma_EyesAnimGeo.geometry}
          material={materials.FitGrandma_Eyes_MAT1}
        />
        <mesh
          name="Fitness_Grandma_MouthAnimGeo"
          geometry={nodes.Fitness_Grandma_MouthAnimGeo.geometry}
          material={materials.FitGrandma_Mouth_MAT1}
        />
        <mesh
          name="Fitness_Grandma_BrowsAnimGeo"
          geometry={nodes.Fitness_Grandma_BrowsAnimGeo.geometry}
          material={materials.FitGrandma_Brows_MAT1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/deoC2.gltf");
