/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 wassenC2.gltf 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function WassenC2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/wassenC2.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["wassen"].play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorig6Hips} />
          <skinnedMesh
            name="Ch09"
            geometry={nodes.Ch09.geometry}
            material={materials.Ch09_body}
            skeleton={nodes.Ch09.skeleton}
          />
        </group>
        <group
          name="Rokoko_Video_Character"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="Root">
            <primitive object={nodes.Hips} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/wassenC2.gltf");
