/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 poetsenC2.gltf 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function PoetsenC2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/poetsenC2.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["poetsen"].play();
    // console.log(actions);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorig6Hips} />
          <skinnedMesh
            name="Ch09"
            geometry={nodes.Ch09.geometry}
            material={materials.Ch09_body}
            skeleton={nodes.Ch09.skeleton}
          />
        </group>
        <group name="Armature001" scale={0.01}>
          <primitive object={nodes._1Root} />
          <skinnedMesh
            name="preretarget_visual_0_L_Wrist3"
            geometry={nodes.preretarget_visual_0_L_Wrist3.geometry}
            material={materials["MoveBotMaterial.008"]}
            skeleton={nodes.preretarget_visual_0_L_Wrist3.skeleton}
          />
          <skinnedMesh
            name="preretarget_visual_0_R_Wrist3"
            geometry={nodes.preretarget_visual_0_R_Wrist3.geometry}
            material={materials["MoveBotMaterial.016"]}
            skeleton={nodes.preretarget_visual_0_R_Wrist3.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/poetsenC2.gltf");
